import { jsPDF } from "jspdf";

export function generateCaseworkerLetter({ clientName = "", purpose = "shelter" }) {
  const doc = new jsPDF({ unit: "pt", format: "letter" });
  const marginLeft = 60;
  let y = 60;

  const line = (text, opts = {}) => {
    const { size = 11, bold = false, gap = 18, color = "#000000" } = opts;
    doc.setFontSize(size);
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setTextColor(color);
    const wrapped = doc.splitTextToSize(text, 495);
    doc.text(wrapped, marginLeft, y);
    y += gap * wrapped.length;
  };

  line("[ORGANIZATION NAME / SHELTER LETTERHEAD]", {
    size: 14,
    bold: true,
    gap: 20,
  });
  line("[Address · Phone · Email · HUD CoC Program ID, if applicable]", {
    size: 9,
    color: "#666666",
    gap: 24,
  });

  line("CASEWORKER IDENTITY VERIFICATION LETTER", {
    size: 15,
    bold: true,
    gap: 30,
  });

  line(`Date: ${new Date().toLocaleDateString("en-US")}`, { gap: 24 });

  line("To: [ ] California Department of Motor Vehicles", { gap: 16 });
  line("     [ ] County Office of Vital Records", { gap: 16 });
  line("     [ ] Other agency: ____________________________", { gap: 28 });

  line(
    "I, the undersigned, am a case manager / outreach worker currently providing services to the individual identified below. I am submitting this letter to support their request for identity documentation, in accordance with applicable state provisions permitting caseworker attestation of identity and housing status where the applicant lacks standard identifying documents.",
    { gap: 15 }
  );

  y += 10;
  line("CLIENT INFORMATION", { bold: true, size: 12, gap: 20 });
  line(`Full legal name (as known): ${clientName || "____________________________"}`, {
    gap: 18,
  });
  line("Date of birth (if known): ____________________________", { gap: 18 });
  line("Current housing status: [ ] Currently in emergency shelter", { gap: 16 });
  line("     [ ] Currently unsheltered, receiving outreach services", { gap: 26 });

  line("PURPOSE OF REQUEST", { bold: true, size: 12, gap: 20 });
  line(
    "[ ] Application for a California state ID (Vehicle Code §14902 fee waiver for individuals experiencing homelessness)",
    { gap: 16 }
  );
  line(
    "[ ] Request for a certified copy of a birth certificate where standard proof of identity is unavailable",
    { gap: 16 }
  );
  line("[ ] Verification of current address for shelter/program intake purposes", {
    gap: 26,
  });

  line("CASEWORKER ATTESTATION", { bold: true, size: 12, gap: 20 });
  line(
    "I attest, to the best of my knowledge and based on my direct working relationship with this individual, that the information above is accurate.",
    { gap: 15 }
  );

  y += 20;
  line("_______________________________", { gap: 16 });
  line("Caseworker signature", { size: 9, color: "#666666", gap: 24 });
  line("_______________________________", { gap: 16 });
  line("Printed name / Title / Organization", { size: 9, color: "#666666", gap: 24 });

  doc.setFontSize(8);
  doc.setTextColor("#999999");
  doc.text(
    "Generated by Documentation Pathway Navigator — informational aid only, not legal advice. Verify current requirements with the receiving agency.",
    marginLeft,
    760,
    { maxWidth: 495 }
  );

  doc.save("Caseworker_Identity_Verification_Letter.pdf");
}
